language: php
php:
  - 5.6
  - 7.0
  - 7.1
env:
  - LARAVEL_VERSION=5.2
  - LARAVEL_VERSION=5.3
  - LARAVEL_VERSION=5.4

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true

before_script:
  - chmod +x scripts/change-laravel-version.sh && bash scripts/change-laravel-version.sh
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpspec run --format=pretty

notifications:
  slack:
    secure: MT5eWBoLLafyRTdFVyig9A/kw68UuKxSiFwFfsd7RaJwJlnR31rfw3oTS6/74Fkr7UQNOclUGSxbX10iIkR9I0ktMayMSDrnDZXNLs3Zn5ciGRjo9zIQ+gw0eqmU1hHyVXvG7pSwoLjqihlkO9J6K/1bUhTaHT+OXvKXZOqJ3Os=
